CREATE OR REPLACE VIEW FACT_ORDERS AS
SELECT
	OB.ORDER_ID,
	OB.CUSTOMER_UNIQUE_ID,
	OB.ORDER_PURCHASE_TIMESTAMP,
	OB.ORDER_STATUS,
	OB.TARGET_NEGATIVE_REVIEW,
	-- Customer Features
	DC.PREVIOUS_ORDERS,
	DC.REPEAT_CUSTOMER,
	DC.PREVIOUS_AVG_REVIEW,
	DC.PREVIOUS_NEGATIVE_RATE,
	DC.DAYS_SINCE_PREVIOUS_ORDER,
	-- Delivery Features
	DD.APPROVAL_TIME_HOURS,
	DD.CARRIER_DELIVERY_HOURS,
	DD.DELIVERY_TIME_DAYS,
	DD.ESTIMATED_DELIVERY_DAYS,
	DD.DELIVERY_DELAY_DAYS,
	DD.IS_DELAYED,
	-- Payment Features
	DP.TOTAL_PAYMENT,
	DP.PAYMENT_COUNT,
	DP.MAX_INSTALLMENTS,
	DP.AVG_INSTALLMENTS,
	DP.PAYMENT_TYPE_COUNT,
	DP.MAIN_PAYMENT_TYPE,
	-- Product Features
	DPR.TOTAL_ITEMS,
	DPR.UNIQUE_PRODUCTS,
	DPR.UNIQUE_CATEGORIES,
	DPR.TOTAL_PRICE,
	DPR.AVERAGE_ITEM_PRICE,
	DPR.TOTAL_WEIGHT,
	DPR.AVERAGE_WEIGHT,
	DPR.TOTAL_VOLUME,
	DPR.MAIN_CATEGORY,
	-- Seller Features
	DS.SELLERS_COUNT,
	DS.MULTIPLE_SELLERS,
	DS.AVG_PREVIOUS_SELLER_ORDERS,
	DS.AVG_SELLER_REVIEW,
	DS.MAX_SELLER_NEGATIVE_RATE,
	DS.AVG_SELLER_DELIVERY_DAYS,
	DS.AVG_SELLER_ORDER_VALUE
FROM
	ORDER_BASE OB
	LEFT JOIN DIM_CUSTOMER DC ON OB.ORDER_ID = DC.ORDER_ID
	LEFT JOIN DIM_DELIVERY DD ON OB.ORDER_ID = DD.ORDER_ID
	LEFT JOIN DIM_PAYMENT DP ON OB.ORDER_ID = DP.ORDER_ID
	LEFT JOIN DIM_PRODUCT DPR ON OB.ORDER_ID = DPR.ORDER_ID
	LEFT JOIN DIM_SELLER DS ON OB.ORDER_ID = DS.ORDER_ID;