CREATE OR REPLACE VIEW CUSTOMER_HISTORY AS
SELECT
	C.CUSTOMER_UNIQUE_ID,
	O.ORDER_ID,
	O.ORDER_PURCHASE_TIMESTAMP,
	R.REVIEW_SCORE,
	ROW_NUMBER() OVER (
		PARTITION BY
			C.CUSTOMER_UNIQUE_ID
		ORDER BY
			O.ORDER_PURCHASE_TIMESTAMP
	) AS ORDER_NUMBER
FROM
	CUSTOMERS C
	JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
	LEFT JOIN REVIEWS R ON O.ORDER_ID = R.ORDER_ID;
