CREATE OR REPLACE VIEW CUSTOMER_FEATURES AS
SELECT
	CUSTOMER_UNIQUE_ID,
	ORDER_ID,
	ORDER_PURCHASE_TIMESTAMP,
	ORDER_NUMBER,
	--Number of previous orders/Количество предыдущих заказов
	GREATEST(ORDER_NUMBER -1, 0) AS PREVIOUS_ORDERS,
	--Repeate customer flag/Флаг повторного клиента
	CASE
		WHEN ORDER_NUMBER > 1 THEN 1
		ELSE 0
	END AS REPEAT_CUSTOMER,
	--Average rating of previous orders/Средний рейтинг предыдущих заказов
	ROUND(
		AVG(REVIEW_SCORE) OVER (
			PARTITION BY
				CUSTOMER_UNIQUE_ID
			ORDER BY
				ORDER_PURCHASE_TIMESTAMP ROWS BETWEEN UNBOUNDED PRECEDING
				AND 1 PRECEDING
		),
		1
	) AS PREV_AVG_SCORE,
	--Negative reviews share/Доля негативных отзывов
	ROUND(
		AVG(
			CASE
				WHEN REVIEW_SCORE IN (1, 2) THEN 1
				ELSE 0
			END
		) OVER (
			PARTITION BY
				CUSTOMER_UNIQUE_ID
			ORDER BY
				ORDER_PURCHASE_TIMESTAMP ROWS BETWEEN UNBOUNDED PRECEDING
				AND 1 PRECEDING
		),
		1
	) AS NEGATIVE_REVIEWS_RATE,
	-- Days since prev order/Кол-во дней с предыдущего заказа
	EXTRACT(
		DAY
		FROM
			ORDER_PURCHASE_TIMESTAMP - LAG(ORDER_PURCHASE_TIMESTAMP) OVER (
				PARTITION BY
					CUSTOMER_UNIQUE_ID
				ORDER BY
					ORDER_PURCHASE_TIMESTAMP
			)
	) AS DAYS_SINCE_PREV_ORDER
FROM
	CUSTOMER_HISTORY;

