CREATE OR REPLACE VIEW DIM_PRODUCT AS
WITH
	ORDER_PRODUCTS AS (
		SELECT
			OI.ORDER_ID,
			OI.PRODUCT_ID,
			OI.PRICE,
			OI.FREIGHT_VALUE,
			P.PRODUCT_CATEGORY_NAME,
			CT.PRODUCT_CATEGORY_NAME_ENGLISH,
			P.PRODUCT_WEIGHT_G,
			P.PRODUCT_LENGTH_CM,
			P.PRODUCT_HEIGHT_CM,
			P.PRODUCT_WIDTH_CM,
			(
				P.PRODUCT_LENGTH_CM * P.PRODUCT_HEIGHT_CM * P.PRODUCT_WIDTH_CM
			) AS PRODUCT_VOLUME
		FROM
			ORDER_ITEMS OI
			LEFT JOIN PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
			LEFT JOIN CATEGORY_TRANSLATION CT ON P.PRODUCT_CATEGORY_NAME = CT.PRODUCT_CATEGORY_NAME
	),
	MAIN_CATEGORY AS (
		SELECT
			ORDER_ID,
			PRODUCT_CATEGORY_NAME_ENGLISH,
			ROW_NUMBER() OVER (
				PARTITION BY
					ORDER_ID
				ORDER BY
					SUM(PRICE) DESC,
					PRODUCT_CATEGORY_NAME_ENGLISH ASC
			) AS RN
		FROM
			ORDER_PRODUCTS
		GROUP BY
			ORDER_ID,
			PRODUCT_CATEGORY_NAME_ENGLISH
	)
SELECT
	OP.ORDER_ID,
	COUNT(*) AS TOTAL_ITEMS,
	COUNT(DISTINCT OP.PRODUCT_ID) AS UNIQUE_PRODUCTS,
	COUNT(DISTINCT OP.PRODUCT_CATEGORY_NAME_ENGLISH) AS UNIQUE_CATEGORIES,
	SUM(OP.PRICE) AS TOTAL_PRICE,
	AVG(OP.PRICE) AS AVERAGE_ITEM_PRICE,
	MAX(OP.PRICE) AS MAX_ITEM_PRICE,
	MIN(OP.PRICE) AS MIN_ITEM_PRICE,
	SUM(OP.FREIGHT_VALUE) AS TOTAL_FREIGHT,
	SUM(OP.PRODUCT_WEIGHT_G) AS TOTAL_WEIGHT,
	AVG(OP.PRODUCT_WEIGHT_G) AS AVERAGE_WEIGHT,
	MAX(OP.PRODUCT_WEIGHT_G) AS MAX_WEIGHT,
	SUM(OP.PRODUCT_VOLUME) AS TOTAL_VOLUME,
	AVG(OP.PRODUCT_VOLUME) AS AVERAGE_VOLUME,
	MAX(MC.PRODUCT_CATEGORY_NAME_ENGLISH) AS MAIN_CATEGORY
FROM
	ORDER_PRODUCTS OP
	LEFT JOIN MAIN_CATEGORY MC ON OP.ORDER_ID = MC.ORDER_ID
	AND MC.RN = 1
GROUP BY
	OP.ORDER_ID;

SELECT
	*
FROM
	DIM_PRODUCT