create or replace view dim_seller as 
WITH
	SELLER_HISTORY AS (
		SELECT
			OI.SELLER_ID,
			O.ORDER_ID,
			O.ORDER_PURCHASE_TIMESTAMP,
			S.SELLER_STATE,
			R.REVIEW_SCORE,
			EXTRACT(
				DAY
				FROM
					(
						O.ORDER_DELIVERED_CUSTOMER_DATE - O.ORDER_PURCHASE_TIMESTAMP
					)
			) AS DELIVERY_DAYS,
			SUM(OI.PRICE) OVER (
				PARTITION BY
					O.ORDER_ID
			) AS ORDER_VALUE
		FROM
			ORDER_ITEMS OI
			JOIN ORDERS O ON O.ORDER_ID = OI.ORDER_ID
			LEFT JOIN REVIEWS R ON O.ORDER_ID = R.ORDER_ID
			JOIN SELLERS S ON OI.SELLER_ID = S.SELLER_ID
	),
	SELLER_FEATURES AS (
		SELECT
			SELLER_ID,
			SELLER_STATE,
			ORDER_ID,
			COUNT(*) OVER (
				PARTITION BY
					SELLER_ID
				ORDER BY
					ORDER_PURCHASE_TIMESTAMP ROWS BETWEEN UNBOUNDED PRECEDING
					AND 1 PRECEDING
			) AS PREVIOUS_ORDERS,
			AVG(REVIEW_SCORE) OVER (
				PARTITION BY
					SELLER_ID
				ORDER BY
					ORDER_PURCHASE_TIMESTAMP ROWS BETWEEN UNBOUNDED PRECEDING
					AND 1 PRECEDING
			) AS AVG_REVIEW,
			AVG(
				CASE
					WHEN REVIEW_SCORE <= 2 THEN 1.0
					ELSE 0.0
				END
			) OVER (
				PARTITION BY
					SELLER_ID
				ORDER BY
					ORDER_PURCHASE_TIMESTAMP ROWS BETWEEN UNBOUNDED PRECEDING
					AND 1 PRECEDING
			) AS NEGATIVE_RATE,
			AVG(DELIVERY_DAYS) OVER (
				PARTITION BY
					SELLER_ID
				ORDER BY
					ORDER_PURCHASE_TIMESTAMP ROWS BETWEEN UNBOUNDED PRECEDING
					AND 1 PRECEDING
			) AS AVG_DELIVERY,
			AVG(ORDER_VALUE) OVER (
				PARTITION BY
					SELLER_ID
				ORDER BY
					ORDER_PURCHASE_TIMESTAMP ROWS BETWEEN UNBOUNDED PRECEDING
					AND 1 PRECEDING
			) AS AVG_ORDER_VALUE
		FROM
			SELLER_HISTORY
	)
SELECT
	ORDER_ID,
	COUNT(DISTINCT SELLER_ID) AS SELLERS_COUNT,
	COUNT(DISTINCT SELLER_STATE) AS SELLER_STATES_COUNT,
	CASE
		WHEN COUNT(DISTINCT SELLER_ID) > 1 THEN 1
		ELSE 0
	END AS MULTIPLE_SELLERS,
	AVG(PREVIOUS_ORDERS) AS AVG_PREVIOUS_SELLER_ORDERS,
	AVG(AVG_REVIEW) AS AVG_SELLER_REVIEW,
	MAX(NEGATIVE_RATE) AS MAX_SELLER_NEGATIVE_RATE,
	AVG(AVG_DELIVERY) AS AVG_SELLER_DELIVERY_DAYS,
	AVG(AVG_ORDER_VALUE) AS AVG_SELLER_ORDER_VALUE
FROM
	SELLER_FEATURES
GROUP BY
	ORDER_ID;

